package y111studios;

import lombok.Getter;

/**
 * AssetPaths class used to store the paths to the assets used in the game.
 * 
 * <p>
 * This class is used to store the constant paths to the internal assets to
 * reduce the occurrence of
 * magic strings in the code.
 * </p>
 */
@Getter
public enum AssetPaths {
  START_SCREEN("assets/StartScreen.png"),
  MAP_BACKGROUND_TOP_LEFT("assets/UnisimMapTL.png"),
  MAP_BACKGROUND_TOP_RIGHT("assets/UnisimMapTR.png"),
  MAP_BACKGROUND_BOTTOM_LEFT("assets/UnisimMapBL.png"),
  MAP_BACKGROUND_BOTTOM_RIGHT("assets/UnisimMapBR.png"),
  SNOWY_MAP_BACKGROUD_TOP_LEFT("assets/UnisimMapTL_Snow_final.png"),
  SNOWY_MAP_BACKGROUD_TOP_RIGHT("assets/UnisimMapTR_Snow_final.png"),
  SNOWY_MAP_BACKGROUD_BOTTOM_LEFT("assets/UnisimMapBL_Snow_final.png"),
  SNOWY_MAP_BACKGROUD_BOTTOM_RIGHT("assets/UnisimMapBR_Snow_final.png"),
  FLOODED_MAP_BACKGROUD_TOP_LEFT("assets/UnisimMapTL_flood_final.png"),
  FLOODED_MAP_BACKGROUD_TOP_RIGHT("assets/UnisimMapTR_flood_final.png"),
  FLOODED_MAP_BACKGROUD_BOTTOM_LEFT("assets/UnisimMapBL_flood_final.png"),
  FLOODED_MAP_BACKGROUD_BOTTOM_RIGHT("assets/UnisimMapBR_flood_final.png"),
  OBSTACLE1("assets/obstacle1.png"),
  OBSTACLE2("assets/obstacle2.png"),
  OBSTACLE3("assets/obstacle3.png"),
  OBSTACLE4("assets/obstacle4.png"),
  OBSTACLE1FLOOD("assets/Obstacle1Flood.png"),
  OBSTACLE2FLOOD("assets/Obstacle2Flood.png"),
  OBSTACLE3FLOOD("assets/Obstacle3Flood.png"),
  OBSTACLE4FLOOD("assets/Obstacle4Flood.png"),
  OBSTACLE1SNOW("assets/Obstacle1Snow.png"),
  OBSTACLE2SNOW("assets/Obstacle2Snow.png"),
  OBSTACLE3SNOW("assets/Obstacle3Snow.png"),
  OBSTACLE4SNOW("assets/Obstacle4Snow.png"),
  MENU_BACKGROUND("assets/MenuBackground.png"),
  MENU_UNSELECTED_TAB("assets/MenuUnselectedTab.png"),
  MENU_SELECTED_TAB("assets/MenuSelectedTab.png"),
  ACCOMMODATION_MENU("assets/Accommodation.png"),
  CATERING_MENU("assets/Catering.png"),
  TEACHING_MENU("assets/Teaching.png"),
  PAUSE("assets/Pause.png"),
  ACC1("assets/Accommodation_1.png"),
  ACC2("assets/Acc2.png"),
  ACC3("assets/Acc3.png"),
  ACC4("assets/Acc4.png"),
  ACC5("assets/Acc5.png"),
  ACC1SNOW("assets/Accommodation_1SnowDetail.png"),
  ACC2SNOW("assets/Acc2SnowDetail.png"),
  ACC3SNOW("assets/Acc3SnowDetail.png"),
  ACC4SNOW("assets/Acc4SnowDetail.png"),
  ACC5SNOW("assets/Acc5SnowDetail.png"),
  CATER1("assets/CATER_1.png"),
  CATER2("assets/CATER_2.png"),
  CATER3("assets/CATER_3.png"),
  CATER4("assets/CATER_4.png"),
  CATER5("assets/Cater5.png"),
  CATER1SNOW("assets/Cater_1Snow.png"),
  CATER2SNOW("assets/Cater_2Snow.png"),
  CATER3SNOW("assets/Cater_3Snow.png"),
  CATER4SNOW("assets/Cater_4Snow.png"),
  CATER5SNOW("assets/Cater_5Snow.png"),
  REC1("assets/Rec1.png"),
  REC2("assets/Rec2.png"),
  REC1SNOW("assets/Rec1Snow.png"),
  REC2SNOW("assets/Rec2Snow.png"),
  TREE1("assets/tree1.png"),
  TREE2("assets/tree3.png"),
  TREE3("assets/tree_8_2.png"),
  TREE1SNOW("assets/Tree_1Snow.png"),
  TREE2SNOW("assets/Tree_3Snow.png"),
  TREE3SNOW("assets/Tree_8Snow.png"),
  TEACH1("assets/Teach1.png"),
  TEACH2("assets/Teach2.png"),
  TEACH3("assets/TEACH_3.png"),
  TEACH4("assets/TEACH_4.png"),
  TEACH5("assets/Teach5.png"),
  TEACH1SNOW("assets/TEACH_1SNOW.png"),
  TEACH2SNOW("assets/TEACH_2SNOW.png"),
  TEACH3SNOW("assets/TEACH_3SNOW.png"),
  TEACH4SNOW("assets/TEACH_4SNOW.png"),
  TEACH5SNOW("assets/TEACH_5SNOW.png"),
  BIKE_SHED("assets/bike_shed.png"),
  BIKE_SHEDSNOW("assets/bike_shedSnow.png"),
  STRAIGHT_ROAD("assets/road1.png"),
  STRAIGHT_ROAD2("assets/road2.png"),
  ROAD_CROSS("assets/road5.png"),
  ROAD_BEND1("assets/road4.png"),
  ROAD_BEND2_FLIPPED("assets/road6.png"),
  ROAD_BEND2("assets/road7.png"),
  STRAIGHT_ROADSNOW("assets/Road_1Snow.png"),
  ROAD_CROSSSNOW("assets/Road_3Snow.png"),
  ROAD_BEND1SNOW("assets/Road_2Snow.png"),
  ROAD_BEND2SNOW("assets/Road_4Snow.png"),
  GAME_OVER("assets/GameOver.png"),
  TRASH("assets/Trash.png"),
  ROTATE("assets/axis-z-rotate-clockwise.png"),
  UNISIM_LOGO("assets/UnisimLogo.png"),
  INSTRUCTIONS("assets/Instructions.png"),
  INFO_BAR_BACKGROUND("assets/InfoBarBackground.png"),
  MUTE_BUTTON("assets/volume-mute-filled.png"),
  UNMUTE_BUTTON("assets/volume-up-filled.png"),
  PAUSE_BUTTON("assets/pause-filled.png"),
  PLAY_BUTTON("assets/play-filled-alt.png"),
  LEADERBOARD_TITLE("assets/LeaderboardTitle.png"),
  ACHIEVEMENT_NOTIFICATION("assets/AchievementNotification.png"),
  SNOWFLAKE("assets/snowflake.png"),
  RAINDROP("assets/raindrop.png"),
  SNOW_EVENT("assets/events/SnowEvent.png"),
  PANDEMIC_EVENT("assets/events/PandemicEvent.png"),
  OPEN_DAY_EVENT("assets/events/OpenDayEvent.png");

  private final String path;

  AssetPaths(String path) {
    this.path = path;
  }
}
