# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Test with Maven
      run: mvn test --file pom.xml
    - name: JUnit Test Report
      uses: mikepenz/action-junit-report@v5.0.0
      with:
        report_paths: "**/target/surefire-reports/TEST-*.xml"
    - name: Upload JaCoCo Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/jacoco/
    - name: Upload Checkstyle Report
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle.html
        path: target/checkstyle.html
  build:
    needs: [test]
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: unisim-0.1.0.jar
        path: target/unisim-0.1.0.jar

  release:
    needs: [build]
    runs-on: [ubuntu-latest]
    # run the release job when a new release tag is added
    if: github.ref_type == 'tag' && contains(github.ref_name, 'release')
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: unisim-0.1.0.jar
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2.1.0
      with:
        # Preserve the order of the artifacts when uploading
        preserve_order: true
        # Repository to make releases against, in <owner>/<repo> format
        repository: JD760/unisim-assessment-2
        # Whether to automatically generate the name and body for this release. If name is specified, the specified name will be used; otherwise, a name will be automatically generated. If body is specified, the body will be pre-pended to the automatically generated notes.
        generate_release_notes: true
        # Specifies whether this release should be set as the latest release for the repository. Drafts and prereleases cannot be set as latest. Can be `true`, `false`, or `legacy`. Uses GitHub api default if not provided
        make_latest: true
        files:
          unisim-0.1.0.jar
          
    
